[package]
name = "lantern_code_annotation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxc_span = "0.12.1"
colored = "2.0.4"

lantern_testing = { path = "../lantern_testing" }
